### PR TITLE
feat: add function to extract information from a model

### PR DESCRIPTION
**Pull request by be-marc**

### CODE REVIEW

**Comment by be-marc** [comment]
Closes https://github.com/mlr-org/mlr3/issues/1013 and https://github.com/mlr-org/mlr3/issues/899

**Comment by be-marc** [comment]
```R
learner = lrn("classif.rpart")
task = tsk("iris")
resampling = rsmp("cv", folds = 3)

extractor = function(learner) list(selected_features = setdiff(learner$model$frame$var, "<leaf>"))

rr = resample(task, learner, resampling, extractor = extractor)
rr$learners[[1]]$state$selected_features
```

**Comment by berndbischl** [comment]
it is not doced where the result of extract is stored

**Comment by berndbischl** [comment]
also always doc the signature of the function

**Comment by berndbischl** [comment]
also there should be a use case example and test. this should include a benchmark.

a user needs to somehow practilly gain access to the extracted stuff at the end

**Comment by be-marc** [comment]
We will implement #1214  instead.

**Pull request closed without merging**
