### PR TITLE
Add example to README

### PR DESCRIPTION
**Pull request by jakob-r**
Can someone check if this is sufficient?

### CODE REVIEW

**Comment by jakob-r** [comment]
Preview can be seen in the branch:

**Comment by pfistfl** [comment]
Some suggestions: 
-> A flashy picture in the header would be really cool
-> Why id = cars?
-> Maybe have a subsubsection between train/test and resampling

**Comment by pfistfl** [comment]
The old mlr repo has some more things we might want to add: https://github.com/mlr-org/mlr
- Blog 
- Slack

**Comment by mllg** [comment]
We have a SO hashtag: `"mlr3"`. Can you add this?

**Comment by jakob-r** [comment]
Should be mergable. Other thigs can be done later I guess.

**Pull request merged**
