### PR TITLE
openml integration

### PR DESCRIPTION
**Pull request by mb706**
Could be its own package but that would probably look similar to this. Maybe someone (a hiwi?) wants to go on working with this.
Inspired by #119

### CODE REVIEW

**Comment by mb706** [comment]
```r
> ts = tsk("openml", 261)
trying URL 'https://www.openml.org/data/v1/download/31/credit-g.arff'
Content type 'text/plain;charset=UTF-8' length 162291 bytes (158 KB)
==================================================
downloaded 158 KB

Parse with reader=readr : /tmp/Rtmp41jsuQ/file35862627d240
header: 0.025000; preproc: 0.000000; data: 0.005000; postproc: 0.001000; total: 0.031000
> rs = rsmp("openml", 261)
trying URL 'https://www.openml.org/api_splits/get/261/Task_261_splits.arff'
Content type 'text/plain;charset=UTF-8' length 13697 bytes (13 KB)
==================================================
downloaded 13 KB

Parse with reader=readr : /tmp/Rtmp41jsuQ/file35867427818f
header: 0.001000; preproc: 0.001000; data: 0.003000; postproc: 0.000000; total: 0.005000
> resample(ts, lrn("classif.rpart"), rs)$aggregate()
INFO  [12:52:17.639] Applying learner 'classif.rpart' on task 'openml_credit-g' (iter 1/1) 
classif.ce 
 0.2909091 
```

**Comment by mb706** [comment]
Currently missing:
* caching
* giving resampling an intelligent name from OpenML
* possibly enabling `rsmp("openml")$instantiate(task)` if we save the OpenML Task ID in `task`
* handling task types beyond classification and regression
* using a different farff reader
* putting jsonlite and the farff reader(s) into `Suggests`

**Comment by mb706** [comment]
* controlling verbosity (through logger I presume)
* check if the resampling fold metadata really alsays has the format that I am assuming
* `.combine` function should be possible for resampling in almost all cases

**Comment by mllg** [comment]
There is also https://github.com/mlr-org/mlr3oml/tree/testing. 

And I would like to have it in an extra package I guess. Without the extra dependencies it is not usable.

**Comment by mb706** [comment]
Hm wasn't aware of the state of mlr3oml. I think I like the `tsk("openml", ...)` interface I show here, maybe some of the ideas here can be ported over there.

**Comment by mllg** [comment]
I've updated https://github.com/mlr-org/mlr3oml and ported the dictionary integration.

**Pull request closed without merging**
