### PR TITLE
Enable parallel tests, 3e adaptions, silence warnings

### PR DESCRIPTION
**Pull request by pat-s**
Parallel testing via {testthat} 3.0

### CODE REVIEW

**Comment by mllg** [comment]
https://github.com/r-lib/testthat/issues/1216

**Comment by pat-s** [comment]
Why not `testthat::test_package("mlr3")`?

**Comment by mllg** [comment]
No possibility to filter the tests with a regular expression.

**Comment by pat-s** [comment]
`test_package()` passes the ellipsis down to `test_dir()` and `testthat::test_package("mlr3", filter = "benchmark")` works just fine for me.

**Comment by mllg** [comment]
`test_package()` looks up the path via `system.file()`. So it does not necessarily test the package in the path (depending on `system.file()` being overloaded by `pkgload` or nor).

**Comment by mllg** [comment]
Does this work for you?

```
> devtools::test()
Loading mlr3
Testing mlr3
Starting 4 test processes
✔ |  OK F W S | Context

══ Results ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 2.4 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]
```

**Comment by mllg** [comment]
IDK, I guess we should wait for 1-2 weeks for the parallel support to mature.

**Comment by pat-s** [comment]
Works just fine for me. Also works on all CI platforms. Looks like a local issue of yours?

**Comment by mllg** [comment]
> Looks like a local issue of yours?

Yep, does not work if called from nvim. :worried:

**Comment by pat-s** [comment]
@mllg Does it work meanwhile?

**Comment by mllg** [comment]
Nope, no fix in testthat.

**Comment by mllg** [comment]
Had some hiccups with nvim, looks like this is resolved by just setting the right option (https://github.com/jalvesaq/Nvim-R/issues/554).

**Pull request merged**
